tags:
  - Enterprise
summary: Update user settings in enterprise
consumes:
  - application/json
security:
  - Bearer: []
parameters:
  - in: path
    name: enterprise_id
    type: string
    required: true
    description: Enterprise id
  - in: path
    name: user_id
    type: string
    required: true
    description: User id
  - in: body
    name: body
    required: true
    schema:
      type: object
      required:
        - settings_data
      properties:
        settings_data:
          type: object
        settings_type:
          type: string
responses:
  200:
    description: Success
  400:
    description: Bad request
  401:
    description: Unauthorized
  500:
    description: Server error
