/**
 * Country → local currency mapping for diet planner budgeting.
 * Symbol is prepended to the budget amount when sent to the backend (e.g. "€150", "$200").
 */

export interface CountryCurrency {
  code: string;
  symbol: string;
  name: string;
}

/** All countries available in the diet planner location dropdown (alphabetical). */
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
  'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
  'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
  'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
  'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
  'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
  'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
  'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
  'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
  'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru',
  'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman',
  'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
  'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
  'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
  'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
] as const;

const DEFAULT_CURRENCY: CountryCurrency = { code: 'USD', symbol: '$', name: 'US Dollar' };

/** Official/local currency for every country in COUNTRIES. */
export const COUNTRY_CURRENCY: Record<string, CountryCurrency> = {
  Afghanistan: { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  Albania: { code: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  Algeria: { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar' },
  Andorra: { code: 'EUR', symbol: '€', name: 'Euro' },
  Angola: { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  'Antigua and Barbuda': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  Argentina: { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso' },
  Armenia: { code: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  Australia: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  Austria: { code: 'EUR', symbol: '€', name: 'Euro' },
  Azerbaijan: { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  Bahamas: { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar' },
  Bahrain: { code: 'BHD', symbol: 'BD', name: 'Bahraini Dinar' },
  Bangladesh: { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  Barbados: { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  Belarus: { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  Belgium: { code: 'EUR', symbol: '€', name: 'Euro' },
  Belize: { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  Benin: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Bhutan: { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  Bolivia: { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  'Bosnia and Herzegovina': { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
  Botswana: { code: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  Brazil: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  Brunei: { code: 'BND', symbol: 'B$', name: 'Brunei Dollar' },
  Bulgaria: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  'Burkina Faso': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Burundi: { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
  'Cabo Verde': { code: 'CVE', symbol: 'Esc', name: 'Cape Verdean Escudo' },
  Cambodia: { code: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  Cameroon: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  Canada: { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  'Central African Republic': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  Chad: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  Chile: { code: 'CLP', symbol: 'CL$', name: 'Chilean Peso' },
  China: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  Colombia: { code: 'COP', symbol: 'COL$', name: 'Colombian Peso' },
  Comoros: { code: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  Congo: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  'Costa Rica': { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  Croatia: { code: 'EUR', symbol: '€', name: 'Euro' },
  Cuba: { code: 'CUP', symbol: '₱', name: 'Cuban Peso' },
  Cyprus: { code: 'EUR', symbol: '€', name: 'Euro' },
  'Czech Republic': { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  'Democratic Republic of the Congo': { code: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
  Denmark: { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  Djibouti: { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  Dominica: { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  'Dominican Republic': { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  Ecuador: { code: 'USD', symbol: '$', name: 'US Dollar' },
  Egypt: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  'El Salvador': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'Equatorial Guinea': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  Eritrea: { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  Estonia: { code: 'EUR', symbol: '€', name: 'Euro' },
  Eswatini: { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni' },
  Ethiopia: { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  Fiji: { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  Finland: { code: 'EUR', symbol: '€', name: 'Euro' },
  France: { code: 'EUR', symbol: '€', name: 'Euro' },
  Gabon: { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  Gambia: { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  Georgia: { code: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  Germany: { code: 'EUR', symbol: '€', name: 'Euro' },
  Ghana: { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  Greece: { code: 'EUR', symbol: '€', name: 'Euro' },
  Grenada: { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  Guatemala: { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  Guinea: { code: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  'Guinea-Bissau': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Guyana: { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar' },
  Haiti: { code: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  Honduras: { code: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  Hungary: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  Iceland: { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  India: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  Indonesia: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  Iran: { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  Iraq: { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  Ireland: { code: 'EUR', symbol: '€', name: 'Euro' },
  Israel: { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  Italy: { code: 'EUR', symbol: '€', name: 'Euro' },
  'Ivory Coast': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Jamaica: { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  Japan: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  Jordan: { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar' },
  Kazakhstan: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  Kenya: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  Kiribati: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  Kuwait: { code: 'KWD', symbol: 'KD', name: 'Kuwaiti Dinar' },
  Kyrgyzstan: { code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som' },
  Laos: { code: 'LAK', symbol: '₭', name: 'Lao Kip' },
  Latvia: { code: 'EUR', symbol: '€', name: 'Euro' },
  Lebanon: { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  Lesotho: { code: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  Liberia: { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar' },
  Libya: { code: 'LYD', symbol: 'LD', name: 'Libyan Dinar' },
  Liechtenstein: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  Lithuania: { code: 'EUR', symbol: '€', name: 'Euro' },
  Luxembourg: { code: 'EUR', symbol: '€', name: 'Euro' },
  Madagascar: { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  Malawi: { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  Malaysia: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  Maldives: { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  Mali: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Malta: { code: 'EUR', symbol: '€', name: 'Euro' },
  'Marshall Islands': { code: 'USD', symbol: '$', name: 'US Dollar' },
  Mauritania: { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  Mauritius: { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  Mexico: { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso' },
  Micronesia: { code: 'USD', symbol: '$', name: 'US Dollar' },
  Moldova: { code: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
  Monaco: { code: 'EUR', symbol: '€', name: 'Euro' },
  Mongolia: { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög' },
  Montenegro: { code: 'EUR', symbol: '€', name: 'Euro' },
  Morocco: { code: 'MAD', symbol: 'DH', name: 'Moroccan Dirham' },
  Mozambique: { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  Myanmar: { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
  Namibia: { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar' },
  Nauru: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  Nepal: { code: 'NPR', symbol: 'रू', name: 'Nepalese Rupee' },
  Netherlands: { code: 'EUR', symbol: '€', name: 'Euro' },
  'New Zealand': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  Nicaragua: { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  Niger: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Nigeria: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  'North Korea': { code: 'KPW', symbol: '₩', name: 'North Korean Won' },
  'North Macedonia': { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  Norway: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  Oman: { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
  Pakistan: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  Palau: { code: 'USD', symbol: '$', name: 'US Dollar' },
  Palestine: { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  Panama: { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  'Papua New Guinea': { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  Paraguay: { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní' },
  Peru: { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  Philippines: { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  Poland: { code: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  Portugal: { code: 'EUR', symbol: '€', name: 'Euro' },
  Qatar: { code: 'QAR', symbol: 'QR', name: 'Qatari Riyal' },
  Romania: { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  Russia: { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  Rwanda: { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc' },
  'Saint Kitts and Nevis': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  'Saint Lucia': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  'Saint Vincent and the Grenadines': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  Samoa: { code: 'WST', symbol: 'WS$', name: 'Samoan Tala' },
  'San Marino': { code: 'EUR', symbol: '€', name: 'Euro' },
  'Sao Tome and Principe': { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  'Saudi Arabia': { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  Senegal: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Serbia: { code: 'RSD', symbol: 'din', name: 'Serbian Dinar' },
  Seychelles: { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
  'Sierra Leone': { code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone' },
  Singapore: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  Slovakia: { code: 'EUR', symbol: '€', name: 'Euro' },
  Slovenia: { code: 'EUR', symbol: '€', name: 'Euro' },
  'Solomon Islands': { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  Somalia: { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling' },
  'South Africa': { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  'South Korea': { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  'South Sudan': { code: 'SSP', symbol: '£', name: 'South Sudanese Pound' },
  Spain: { code: 'EUR', symbol: '€', name: 'Euro' },
  'Sri Lanka': { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
  Sudan: { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
  Suriname: { code: 'SRD', symbol: 'Sr$', name: 'Surinamese Dollar' },
  Sweden: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  Switzerland: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  Syria: { code: 'SYP', symbol: '£S', name: 'Syrian Pound' },
  Taiwan: { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
  Tajikistan: { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni' },
  Tanzania: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  Thailand: { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  'Timor-Leste': { code: 'USD', symbol: '$', name: 'US Dollar' },
  Togo: { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  Tonga: { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  'Trinidad and Tobago': { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  Tunisia: { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar' },
  Turkey: { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  Turkmenistan: { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat' },
  Tuvalu: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  Uganda: { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  Ukraine: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  'United Arab Emirates': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  'United Kingdom': { code: 'GBP', symbol: '£', name: 'British Pound' },
  'United States': { code: 'USD', symbol: '$', name: 'US Dollar' },
  Uruguay: { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
  Uzbekistan: { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som' },
  Vanuatu: { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu' },
  'Vatican City': { code: 'EUR', symbol: '€', name: 'Euro' },
  Venezuela: { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar' },
  Vietnam: { code: 'VND', symbol: '₫', name: 'Vietnamese Đồng' },
  Yemen: { code: 'YER', symbol: '﷼', name: 'Yemeni Rial' },
  Zambia: { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  Zimbabwe: { code: 'USD', symbol: '$', name: 'US Dollar' },
};

export function getCurrencyForCountry(country: string): CountryCurrency {
  if (!country) return DEFAULT_CURRENCY;
  return COUNTRY_CURRENCY[country] ?? DEFAULT_CURRENCY;
}

/** Format budget with currency symbol for the backend, e.g. "€150" or "₦20000". */
export function formatBudgetWithCurrency(amount: string, country: string): string {
  const trimmed = amount.trim();
  if (!trimmed) return trimmed;
  const { symbol } = getCurrencyForCountry(country);
  // Avoid double-prefixing if already present
  if (trimmed.startsWith(symbol)) return trimmed;
  return `${symbol}${trimmed}`;
}
